---
title: Erhan BÜTE
timezone: Europe/Moscow
collections:
  posts:
    title: Posts
    output: true
  tabs:
    title: Tabs
    output: true
    sort_by: order
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    comments: true
    toc: true
    permalink: "/posts/:title/"
- scope:
    path: _drafts
  values:
    comments: false
- scope:
    path: ''
    type: tabs
  values:
    layout: page
    permalink: "/:title/"
theme: jekyll-theme-chirpy
lang: tr
tagline: Software Developer
description: A minimal, responsive and feature-rich Jekyll theme for technical writing.
url: https://erhan.github.io
github:
  username: erhan
twitter:
  username: erhanbute
social:
  name: Erhan BÜTE
  email: erhan@hey.com
  links:
  - https://twitter.com/erhanbute
  - https://github.com/erhan
webmaster_verifications:
  google: 
  bing: 
  alexa: 
  yandex: 
  baidu: 
  facebook: 
analytics:
  google:
    id: 
  goatcounter:
    id: 
  umami:
    id: 
    domain: 
  matomo:
    id: 
    domain: 
  cloudflare:
    id: 
  fathom:
    id: 
pageviews:
  provider: 
theme_mode: 
cdn: 
avatar: 
social_preview_image: 
toc: true
comments:
  provider: 
  disqus:
    shortname: 
  utterances:
    repo: 
    issue_term: 
  giscus:
    repo: 
    repo_id: 
    category: 
    category_id: 
    mapping: 
    strict: 
    input_position: 
    lang: 
    reactions_enabled: 
assets:
  self_host:
    enabled: 
    env: 
pwa:
  enabled: true
  cache:
    enabled: true
    deny_paths: 
paginate: 10
baseurl: 
kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
sass:
  style: compressed
compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs:
    - development
exclude:
- "*.gem"
- "*.gemspec"
- docs
- tools
- README.md
- LICENSE
- purgecss.js
- rollup.config.js
- package*.json
jekyll-archives:
  enabled:
  - categories
  - tags
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: "/tags/:name/"
    category: "/categories/:name/"
